export default {
	SelectLanguage: 'SelectLanguage',
	Loading: 'Loading',
	SelectAccount: 'SelectAccount',
	LandingScreen: 'LandingScreen',
	SignUp: 'SignUp',
	OTPMobileNumber: 'OTPMobileNumber',
	VerifyOTP: 'VerifyOTP',
	Login: 'Login',
	RegisterDocuments: 'RegisterDocuments',
	RegisterPersonalInfor: 'RegisterPersonalInfor',
	RegisterLocation: 'RegisterLocation',
	OpenCamera: 'OpenCamera',
	SuccessRegistration: 'SuccessRegistration',
};
